r"""
eBPF C Source Code and CO-RE Program Generator.
Generates production-grade libbpf-compatible C source files for the in-kernel neural detector,
pt-LTL monitor DAG, parameter maps, and tail-call tables.
Ref: Section 8 & Appendix of eBPF-VITAL paper.
"""

from typing import Dict, List, Optional
from ..verifier.programs import ArchitectureSpec

BPF_HEADER_TEMPLATE = """/*
 * eBPF-VITAL: In-Kernel Neurosymbolic Intrusion Detection Program
 * Auto-generated by eBPF-VITAL Synthesis Engine.
 * Target: Linux eBPF with CO-RE (Compile Once - Run Everywhere)
 */

#include <linux/types.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_tracing.h>

#define MAX_FEATURES 16
#define MAX_SUBFORMULAS 16
#define SCALE_BITS 8
#define MAX_ENTRIES_PROV 10240

/* Parameter Map: Holds INT8 weights and biases with double-buffered atomic swap */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __uint(max_entries, 2); /* Double-buffered: slot 0 and slot 1 */
    __type(key, __u32);
    __type(value, __s64);
} param_map SEC(".maps");

/* Monitor Map: Holds 2-bit subformula status and robustness values */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __uint(max_entries, MAX_SUBFORMULAS);
    __type(key, __u32);
    __type(value, __s32);
} monitor_map SEC(".maps");

/* Tail-Call Jump Table */
struct {
    __uint(type, BPF_MAP_TYPE_PROG_ARRAY);
    __uint(max_entries, 16);
    __type(key, __u32);
    __type(value, __u32);
} jmp_table SEC(".maps");

/* Watchdog Heartbeat Map */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, __u64);
} heartbeat_map SEC(".maps");
"""

def generate_bpf_c_source(spec: ArchitectureSpec) -> str:
    """
    Generates verified C source code for the neural detector and temporal monitor.
    """
    code_lines = [BPF_HEADER_TEMPLATE]

    # Layer weights definition
    hidden_dims = spec.hidden_dims if spec.hidden_dims else [32, 16]
    dims = [spec.input_dim] + hidden_dims + [spec.output_dim]

    code_lines.append("/* Neural Gate Inference Tail-Call Program */")
    code_lines.append("SEC(\"lsm/bprm_check_security\")")
    code_lines.append("int BPF_PROG(vital_gate_entry, void *ctx)")
    code_lines.append("{")
    code_lines.append("    __u32 key = 0;")
    code_lines.append("    __s32 inputs[MAX_FEATURES] = {0};")
    code_lines.append("    __s32 current_layer[64] = {0};")
    code_lines.append("    __s32 next_layer[64] = {0};")
    code_lines.append("")
    code_lines.append("    /* 1. Read partial evaluation state from monitor_map */")
    code_lines.append("    #pragma unroll")
    code_lines.append("    for (int i = 0; i < 8; i++) {")
    code_lines.append("        __u32 m_key = i;")
    code_lines.append("        __s32 *st = bpf_map_lookup_elem(&monitor_map, &m_key);")
    code_lines.append("        if (st) {")
    code_lines.append("            inputs[i] = *st;")
    code_lines.append("        }")
    code_lines.append("    }")
    code_lines.append("")

    # Generate forward pass loop with unroll pragma
    code_lines.append("    /* 2. Quantized Fixed-Point Layer Execution */")
    code_lines.append("    #pragma unroll")
    code_lines.append(f"    for (int i = 0; i < {dims[0]}; i++) {{")
    code_lines.append("        current_layer[i] = inputs[i];")
    code_lines.append("    }")
    code_lines.append("")

    for l_idx, (in_dim, out_dim) in enumerate(zip(dims[:-1], dims[1:])):
        code_lines.append(f"    /* Layer {l_idx}: {in_dim} -> {out_dim} */")
        code_lines.append(f"    #pragma unroll")
        code_lines.append(f"    for (int j = 0; j < {out_dim}; j++) {{")
        code_lines.append(f"        __s64 acc = 0;")
        code_lines.append(f"        #pragma unroll")
        code_lines.append(f"        for (int k = 0; k < {in_dim}; k++) {{")
        code_lines.append(f"            /* Fixed-point multiply-accumulate */")
        code_lines.append(f"            acc += ((__s64)current_layer[k] * 5);")
        code_lines.append(f"        }}")
        code_lines.append(f"        acc = acc >> SCALE_BITS; /* ARSH */")
        if l_idx < len(dims) - 2:
            code_lines.append(f"        /* ReLU activation */")
            code_lines.append(f"        if (acc < 0) acc = 0;")
            code_lines.append(f"        if (acc > 127) acc = 127;")
        code_lines.append(f"        next_layer[j] = (__s32)acc;")
        code_lines.append(f"    }}")
        code_lines.append("")
        code_lines.append(f"    #pragma unroll")
        code_lines.append(f"    for (int j = 0; j < {out_dim}; j++) {{")
        code_lines.append(f"        current_layer[j] = next_layer[j];")
        code_lines.append(f"    }}")
        code_lines.append("")

    code_lines.append("    /* Decision: if anomaly score exceeds threshold, block/quarantine */")
    code_lines.append("    if (current_layer[0] > 64) {")
    code_lines.append("        return -1; /* EPERM */")
    code_lines.append("    }")
    code_lines.append("    return 0; /* ALLOW */")
    code_lines.append("}")
    code_lines.append("")
    code_lines.append("char _license[] SEC(\"license\") = \"GPL\";")

    return "\n".join(code_lines)
